In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
import sys
sys.path.append('../scripts/utils')

from barcode_annotation import annotate_barcodes

Comparing Coverage and Quality of Deep CapWGS of HSCs to paired bulk, and publicly available single cell WGA data from MALBAC, MDA, PTA, and LIANTI

Public WGA data: `../data/public_WGA`

HSC data:        `../data/HSC`

In [3]:
bcs = pd.read_csv('../barcodes/map.csv')
bcs

,Unnamed: 0,1,2,3,4,5,6,7,8,9,10,11,12
0,A,GTAACCGA,TCCTCAAC,TGGTCTCA,TACAACCG,TCTGGAAC,GCAATGAC,TACAGCAG,GGAACCAA,GGACGAAT,GTAATGCC,GTGGTGAT,CGACAGTA
1,B,GTCCGATT,TTGACCAC,TCCAGGAT,CGCCAATA,TCTGCTTG,AGACGAAC,CTGCTCAA,CGACATTC,TTGGTAGC,GTGTAAGC,TGTGGTTG,ACCTCGTA
2,C,GACAGCAT,GATGGTCT,CATACCGT,GTGTGATG,GGAACTGT,GCTGGATA,CGCTACTA,CGACAAGA,TTCGGTAG,CGCTAGTT,AATGGCAG,AGGTCCAA
3,D,CGGTTGAT,CGACCTAT,TTCCACTC,CGAACTTG,TCCAGTCT,AGGTCGTA,CTTCAGCA,AACTGCTC,AGACCGAT,GGTCTCAT,TACCACAG,ATACGACC
4,E,CGGTAAGT,GTGACTCT,CTGTGAAC,AGCATTGG,ACAGTAGC,TGCTATGG,AACGATGG,GTCTGCTA,AAGGTGAC,CGGTAGAA,GTGAGACT,TATCAGCC
5,F,TGACAGTG,GGCATCAA,ACATCGTC,TATGCGAC,CATCGTTG,AGAATGCC,AGGCTAAC,GATACCGA,ACCTTCAG,CAACCAAC,ATCGACAG,GGTTGATG
6,G,CACTGACA,AGATACCG,TTGGATGC,CACCATCT,TAACGGAG,AGGACATC,CACCTTGA,TGGTCACT,AGATGGTC,ATATGCGG,GGTCATTG,TATCCGGT
7,H,GTCGGTAA,TTGATGGC,GTTACGGT,CAGGTGAA,AGACACCA,TGTTGGAC,ATGGTGTG,CCATACGA,AGGCATTG,CAACTTGC,ACTAACCG,AAGGCTTG

In [16]:
yeast = pd.read_csv('../results/multispecies_WGA/S_cerevisiae/compiled_qc_metrics.csv', index_col=0)
yeast

,pct_reads_aligned,mean_read_length,reads_aligned,total_reads,at_dropout,gc_dropout,pct_duplicates,read_pairs_examined,read_pair_duplicates,mean_coverage,median_coverage,pct_1x,pct_10x
sample,,,,,,,,,,,,,
AAGGCTTGAGGAACCTTCAGACTCTATGCGACAAGGGTCGGTAAA,1,137.401746,52817,52817,11.749733,0.340261,0.167295,52817,8836,0.294687,0,0.011876,0.002138
AAGGCTTGAGGACACCTTGAACTCCAGGTGAAAAGGGTCCGATTA,1,138.241183,4225,4225,55.006006,1.953186,0.155976,4225,659,0.037040,0,0.001001,0.000543
AAGGCTTGAGGACGACATTCACTCTATGCGACAAGGCGACCTATA,1,135.294049,28077,28077,52.010583,2.595159,0.154824,28077,4347,0.189292,0,0.006145,0.002578
AAGGCTTGAGGAGATACCGAACTCGCTGGATAAAGGGTAACCGAA,1,136.175698,20188,20188,39.845141,2.643535,0.148900,20188,3006,0.117165,0,0.006351,0.002246
AAGGCTTGAGGAGGACGAATACTCTACAACCGAAGGTCCTCAACA,1,136.106802,49175,49175,17.721029,0.382670,0.170269,49175,8373,0.415955,0,0.008606,0.004834
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TATCCGGTAGGAAGGCTAACACTCTCTGCTTGAAGGTGGTCTCAA,1,135.851045,19959,19959,32.634140,2.150275,0.146100,19959,2916,0.132012,0,0.008287,0.003118
TGTGGTTGAGGAAACGATGGACTCAGACACCAAAGGTCCAGGATA,1,136.301614,7871,7871,11.964052,3.014792,0.115741,7871,911,0.008950,0,0.001971,0.000286
TGTGGTTGAGGACCATACGAACTCAGAATGCCAAGGTCCTCAACA,1,137.806223,4949,4949,13.633569,2.984787,0.117802,4949,583,0.005967,0,0.000955,0.000175
TGTGGTTGAGGACGACATTCACTCCATCGTTGAAGGCATACCGTA,1,136.324549,6982,6982,31.599555,1.218907,0.162991,6982,1138,0.057132,0,0.007263,0.002137
TGTGGTTGAGGAGGACGAATACTCCGAACTTGAAGGTTGGATGCA,1,137.817192,320583,320583,1.259961,0.017474,0.160888,320583,51578,2.830001,0,0.418103,0.099275

In [ ]:
yeast = annotate_barcodes(
    yeast, bcs,
    column_name='amplification_method',
    conditions={
        'mMDA': ['A', 'B', 'C', 'D'],
        'PTA':  ['E', 'F', 'G', 'H'],
    },
)