In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
import sys
sys.path.append('../scripts/utils')

from barcode_annotation import annotate_barcodes

Comparing Coverage and Quality of Deep CapWGS of HSCs to paired bulk, and publicly available single cell WGA data from MALBAC, MDA, PTA, and LIANTI

Public WGA data: `../data/public_WGA`

HSC data:        `../data/HSC`

In [22]:
bcs = pd.read_csv('../barcodes/map.csv', index_col=0)
bcs.columns = bcs.columns.astype(int)
bcs

,1,2,3,4,5,6,7,8,9,10,11,12
A,GTAACCGA,TCCTCAAC,TGGTCTCA,TACAACCG,TCTGGAAC,GCAATGAC,TACAGCAG,GGAACCAA,GGACGAAT,GTAATGCC,GTGGTGAT,CGACAGTA
B,GTCCGATT,TTGACCAC,TCCAGGAT,CGCCAATA,TCTGCTTG,AGACGAAC,CTGCTCAA,CGACATTC,TTGGTAGC,GTGTAAGC,TGTGGTTG,ACCTCGTA
C,GACAGCAT,GATGGTCT,CATACCGT,GTGTGATG,GGAACTGT,GCTGGATA,CGCTACTA,CGACAAGA,TTCGGTAG,CGCTAGTT,AATGGCAG,AGGTCCAA
D,CGGTTGAT,CGACCTAT,TTCCACTC,CGAACTTG,TCCAGTCT,AGGTCGTA,CTTCAGCA,AACTGCTC,AGACCGAT,GGTCTCAT,TACCACAG,ATACGACC
E,CGGTAAGT,GTGACTCT,CTGTGAAC,AGCATTGG,ACAGTAGC,TGCTATGG,AACGATGG,GTCTGCTA,AAGGTGAC,CGGTAGAA,GTGAGACT,TATCAGCC
F,TGACAGTG,GGCATCAA,ACATCGTC,TATGCGAC,CATCGTTG,AGAATGCC,AGGCTAAC,GATACCGA,ACCTTCAG,CAACCAAC,ATCGACAG,GGTTGATG
G,CACTGACA,AGATACCG,TTGGATGC,CACCATCT,TAACGGAG,AGGACATC,CACCTTGA,TGGTCACT,AGATGGTC,ATATGCGG,GGTCATTG,TATCCGGT
H,GTCGGTAA,TTGATGGC,GTTACGGT,CAGGTGAA,AGACACCA,TGTTGGAC,ATGGTGTG,CCATACGA,AGGCATTG,CAACTTGC,ACTAACCG,AAGGCTTG

In [33]:
yeast = pd.read_csv('../results/multispecies_WGA/S_cerevisiae/compiled_qc_metrics.csv', index_col=0)
yeast

,pct_reads_aligned,mean_read_length,reads_aligned,total_reads,at_dropout,gc_dropout,pct_duplicates,read_pairs_examined,read_pair_duplicates,mean_coverage,median_coverage,pct_1x,pct_10x,gini_coefficient
barcode,,,,,,,,,,,,,,
AAGGCTTGAGGAACCTTCAGACTCTATGCGACAAGGGTCGGTAAA,1,137.401746,52817,52817,11.749733,0.340261,0.167295,52817,8836,0.294687,0,0.011876,0.002138,0.897535
AAGGCTTGAGGACACCTTGAACTCCAGGTGAAAAGGGTCCGATTA,1,138.241183,4225,4225,55.006006,1.953186,0.155976,4225,659,0.037040,0,0.001001,0.000543,0.893088
AAGGCTTGAGGACGACATTCACTCTATGCGACAAGGCGACCTATA,1,135.294049,28077,28077,52.010583,2.595159,0.154824,28077,4347,0.189292,0,0.006145,0.002578,0.805826
AAGGCTTGAGGAGATACCGAACTCGCTGGATAAAGGGTAACCGAA,1,136.175698,20188,20188,39.845141,2.643535,0.148900,20188,3006,0.117165,0,0.006351,0.002246,0.748462
AAGGCTTGAGGAGGACGAATACTCTACAACCGAAGGTCCTCAACA,1,136.106802,49175,49175,17.721029,0.382670,0.170269,49175,8373,0.415955,0,0.008606,0.004834,0.703449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TATCCGGTAGGAAGGCTAACACTCTCTGCTTGAAGGTGGTCTCAA,1,135.851045,19959,19959,32.634140,2.150275,0.146100,19959,2916,0.132012,0,0.008287,0.003118,0.741460
TGTGGTTGAGGAAACGATGGACTCAGACACCAAAGGTCCAGGATA,1,136.301614,7871,7871,11.964052,3.014792,0.115741,7871,911,0.008950,0,0.001971,0.000286,0.748472
TGTGGTTGAGGACCATACGAACTCAGAATGCCAAGGTCCTCAACA,1,137.806223,4949,4949,13.633569,2.984787,0.117802,4949,583,0.005967,0,0.000955,0.000175,0.710277
TGTGGTTGAGGACGACATTCACTCCATCGTTGAAGGCATACCGTA,1,136.324549,6982,6982,31.599555,1.218907,0.162991,6982,1138,0.057132,0,0.007263,0.002137,0.724274
TGTGGTTGAGGAGGACGAATACTCCGAACTTGAAGGTTGGATGCA,1,137.817192,320583,320583,1.259961,0.017474,0.160888,320583,51578,2.830001,0,0.418103,0.099275,0.469232

In [34]:
yeast = annotate_barcodes(
    yeast, bcs,
    column_name='amplification_method',
    conditions={
        'PTA': ['A', 'B', 'C', 'D'],
        'mMDA':  ['E', 'F', 'G', 'H'],
    },
)

In [35]:
yeast.value_counts('amplification_method')

amplification_method
PTA     85
mMDA    35
Name: count, dtype: int64

In [36]:
yeast.sort_values(by='pct_1x',ascending=False)[:30]

,pct_reads_aligned,mean_read_length,reads_aligned,total_reads,at_dropout,gc_dropout,pct_duplicates,read_pairs_examined,read_pair_duplicates,mean_coverage,median_coverage,pct_1x,pct_10x,gini_coefficient,amplification_method
barcode,,,,,,,,,,,,,,,
TACCACAGAGGACGCTACTAACTCAGCATTGGAAGGCTGTGAACA,1,138.387871,217482,217482,4.116443,0.009644,0.162124,217482,35259,1.890182,1,0.688958,0.006623,0.421368,mMDA
GTGAGACTAGGACCATACGAACTCTCTGCTTGAAGGAGATACCGA,1,137.828492,287585,287585,0.766756,0.117188,0.163680,287585,47072,2.522689,1,0.606056,0.044316,0.439798,mMDA
GTGAGACTAGGAAACGATGGACTCTAACGGAGAAGGGTGACTCTA,1,138.031846,353048,353048,3.603837,0.010386,0.162527,353048,57380,3.031456,1,0.512888,0.094519,0.485240,mMDA
CGCTAGTTAGGAAGATGGTCACTCTATGCGACAAGGTTGATGGCA,1,138.345620,185464,185464,2.013514,0.002826,0.146950,185464,27254,1.669291,0,0.484281,0.024596,0.500335,mMDA
TGTGGTTGAGGAGGACGAATACTCCGAACTTGAAGGTTGGATGCA,1,137.817192,320583,320583,1.259961,0.017474,0.160888,320583,51578,2.830001,0,0.418103,0.099275,0.469232,mMDA
ACCTCGTAAGGAAAGGTGACACTCAGACGAACAAGGTTGATGGCA,1,138.049423,301174,301174,1.068730,0.009226,0.157640,301174,47477,2.661371,0,0.358481,0.103121,0.524194,mMDA
ACCTCGTAAGGAATGGTGTGACTCCACCATCTAAGGCGGTAAGTA,1,137.697853,292513,292513,1.818212,0.406980,0.162311,292513,47478,2.581848,0,0.287524,0.103119,0.506019,mMDA
ACCTCGTAAGGAAACGATGGACTCCGAACTTGAAGGAGATACCGA,1,137.958760,149974,149974,0.936026,0.515369,0.163728,149974,24555,1.337616,0,0.271431,0.039680,0.547689,mMDA
GGTCTCATAGGACGACAAGAACTCAGACGAACAAGGGTGACTCTA,1,137.922800,410698,410698,2.369035,0.009174,0.160493,410698,65914,3.546610,0,0.220898,0.130689,0.558629,mMDA
CAACCAACAGGACACCTTGAACTCTCTGCTTGAAGGCGGTAAGTA,1,138.093735,233082,233082,1.037968,0.390270,0.156687,233082,36521,2.110089,0,0.186087,0.093623,0.441617,mMDA
AGGTCCAAAGGACACCTTGAACTCTCCAGTCTAAGGAGATACCGA,1,137.555804,23260,23260,1.663833,0.154645,0.167627,23260,3899,0.199536,0,0.166754,0.000000,0.414978,mMDA
ATACGACCAGGAATGGTGTGACTCCACCATCTAAGGGTAACCGAA,1,137.390462,453934,453934,7.144855,0.007633,0.161671,453934,73388,3.661176,0,0.151090,0.117510,0.499429,PTA
ACCTCGTAAGGACCATACGAACTCTCTGGAACAAGGGTTACGGTA,1,138.141797,118451,118451,1.445109,0.060702,0.163283,118451,19341,1.036704,0,0.135241,0.041552,0.605320,mMDA
GTGGTGATAGGAATGGTGTGACTCGGAACTGTAAGGGGCATCAAA,1,137.752424,63217,63217,1.429255,0.531302,0.161096,63217,10184,0.551224,0,0.111127,0.013882,0.688674,mMDA
GTGGTGATAGGAGTCTGCTAACTCACAGTAGCAAGGTTGGATGCA,1,137.244957,75850,75850,1.704385,0.728763,0.161094,75850,12219,0.666194,0,0.101716,0.022570,0.745988,mMDA
TACCACAGAGGAGATACCGAACTCAGCATTGGAAGGGTCGGTAAA,1,138.331909,161291,161291,4.593797,0.004101,0.170009,161291,27421,1.173900,0,0.092074,0.008000,0.918580,mMDA
GTGGTGATAGGAGGACGAATACTCAGACGAACAAGGGTTACGGTA,1,137.798189,402332,402332,1.825748,0.702868,0.171972,402332,69190,3.583872,0,0.068315,0.055362,0.651382,mMDA
ATATGCGGAGGATACAGCAGACTCTAACGGAGAAGGGGCATCAAA,1,138.389468,125335,125335,1.660128,0.141111,0.163227,125335,20458,1.087417,0,0.067863,0.045960,0.519468,mMDA
CGACAGTAAGGAAACTGCTCACTCTCCAGTCTAAGGCACTGACAA,1,138.410560,42084,42084,1.995385,0.964743,0.154215,42084,6490,0.381110,0,0.067681,0.012721,0.680063,mMDA
ACCTCGTAAGGACGCTACTAACTCGGAACTGTAAGGCGGTAAGTA,1,137.804705,304175,304175,4.818117,0.959752,0.163271,304175,49663,2.730103,0,0.065585,0.053191,0.613370,mMDA
TATCAGCCAGGAGTCTGCTAACTCCACCATCTAAGGGTGACTCTA,1,137.346724,272721,272721,8.316465,0.022167,0.196659,272721,53633,1.256623,0,0.058855,0.018320,0.928363,mMDA
ATATGCGGAGGAACCTTCAGACTCAGACACCAAAGGTTGATGGCA,1,137.647087,27409,27409,4.011606,0.035904,0.169579,27409,4648,0.235170,0,0.054907,0.007674,0.763475,mMDA
CGCTAGTTAGGATGGTCACTACTCAGGTCGTAAAGGGTAACCGAA,1,137.055406,250931,250931,14.258640,0.011885,0.155752,250931,39083,1.815086,0,0.046141,0.030065,0.655860,PTA
CGACAGTAAGGAAACTGCTCACTCGGAACTGTAAGGGTCCGATTA,1,137.729720,168925,168925,14.463631,0.000593,0.154672,168925,26128,1.210148,0,0.043906,0.027477,0.683558,PTA
ACCTCGTAAGGACACCTTGAACTCTCTGGAACAAGGTCCTCAACA,1,137.556174,167070,167070,3.624941,0.094339,0.155994,167070,26062,1.402610,0,0.041159,0.030078,0.633870,PTA
AGGTCCAAAGGACGACAAGAACTCCAGGTGAAAAGGGTCCGATTA,1,137.423277,502706,502706,12.199365,0.022447,0.152783,502706,76805,2.903404,0,0.037920,0.024797,0.725636,PTA
CAACCAACAGGAAGACCGATACTCTGCTATGGAAGGGTCCGATTA,1,137.453405,587793,587793,13.665994,0.002279,0.163612,587793,96170,3.432682,0,0.037431,0.027952,0.710235,PTA
TATCAGCCAGGAGATACCGAACTCAGGACATCAAGGGTCCGATTA,1,135.967736,784066,784066,30.880658,0.007798,0.174388,784066,136732,3.321688,0,0.036503,0.025089,0.793923,PTA
ATCGACAGAGGATTCGGTAGACTCAGACGAACAAGGACATCGTCA,1,137.587228,33825,33825,2.393305,0.348911,0.166563,33825,5634,0.288014,0,0.033290,0.009096,0.782840,mMDA
CGCTAGTTAGGAAGATGGTCACTCTATGCGACAAGGGGCATCAAA,1,139.811684,4519,4519,1.955827,0.192868,0.151582,4519,685,0.033231,0,0.031553,0.000000,0.321041,mMDA

In [32]:
worms = pd.read_csv('../results/multispecies_WGA/C_elegans/compiled_qc_metrics.csv', index_col=0)
worms

FileNotFoundError: [Errno 2] No such file or directory: '../results/multispecies_WGA/C_elegans/compiled_qc_metrics.csv'

In [23]:
yeast = annotate_barcodes(
    yeast, bcs,
    column_name='amplification_method',
    conditions={
        'PTA': ['A', 'B', 'C', 'D'],
        'mMDA':  ['E', 'F', 'G', 'H'],
    },
)

In [25]:
yeast.value_counts('amplification_method')

amplification_method
PTA     85
mMDA    35
Name: count, dtype: int64

In [30]:
yeast.sort_values(by='pct_1x',ascending=False)[:30]

,pct_reads_aligned,mean_read_length,reads_aligned,total_reads,at_dropout,gc_dropout,pct_duplicates,read_pairs_examined,read_pair_duplicates,mean_coverage,median_coverage,pct_1x,pct_10x,amplification_method
sample,,,,,,,,,,,,,,
TACCACAGAGGACGCTACTAACTCAGCATTGGAAGGCTGTGAACA,1,138.387871,217482,217482,4.116443,0.009644,0.162124,217482,35259,1.890182,1,0.688958,0.006623,mMDA
GTGAGACTAGGACCATACGAACTCTCTGCTTGAAGGAGATACCGA,1,137.828492,287585,287585,0.766756,0.117188,0.163680,287585,47072,2.522689,1,0.606056,0.044316,mMDA
GTGAGACTAGGAAACGATGGACTCTAACGGAGAAGGGTGACTCTA,1,138.031846,353048,353048,3.603837,0.010386,0.162527,353048,57380,3.031456,1,0.512888,0.094519,mMDA
CGCTAGTTAGGAAGATGGTCACTCTATGCGACAAGGTTGATGGCA,1,138.345620,185464,185464,2.013514,0.002826,0.146950,185464,27254,1.669291,0,0.484281,0.024596,mMDA
TGTGGTTGAGGAGGACGAATACTCCGAACTTGAAGGTTGGATGCA,1,137.817192,320583,320583,1.259961,0.017474,0.160888,320583,51578,2.830001,0,0.418103,0.099275,mMDA
ACCTCGTAAGGAAAGGTGACACTCAGACGAACAAGGTTGATGGCA,1,138.049423,301174,301174,1.068730,0.009226,0.157640,301174,47477,2.661371,0,0.358481,0.103121,mMDA
ACCTCGTAAGGAATGGTGTGACTCCACCATCTAAGGCGGTAAGTA,1,137.697853,292513,292513,1.818212,0.406980,0.162311,292513,47478,2.581848,0,0.287524,0.103119,mMDA
ACCTCGTAAGGAAACGATGGACTCCGAACTTGAAGGAGATACCGA,1,137.958760,149974,149974,0.936026,0.515369,0.163728,149974,24555,1.337616,0,0.271431,0.039680,mMDA
GGTCTCATAGGACGACAAGAACTCAGACGAACAAGGGTGACTCTA,1,137.922800,410698,410698,2.369035,0.009174,0.160493,410698,65914,3.546610,0,0.220898,0.130689,mMDA
CAACCAACAGGACACCTTGAACTCTCTGCTTGAAGGCGGTAAGTA,1,138.093735,233082,233082,1.037968,0.390270,0.156687,233082,36521,2.110089,0,0.186087,0.093623,mMDA
AGGTCCAAAGGACACCTTGAACTCTCCAGTCTAAGGAGATACCGA,1,137.555804,23260,23260,1.663833,0.154645,0.167627,23260,3899,0.199536,0,0.166754,0.000000,mMDA
ATACGACCAGGAATGGTGTGACTCCACCATCTAAGGGTAACCGAA,1,137.390462,453934,453934,7.144855,0.007633,0.161671,453934,73388,3.661176,0,0.151090,0.117510,PTA
ACCTCGTAAGGACCATACGAACTCTCTGGAACAAGGGTTACGGTA,1,138.141797,118451,118451,1.445109,0.060702,0.163283,118451,19341,1.036704,0,0.135241,0.041552,mMDA
GTGGTGATAGGAATGGTGTGACTCGGAACTGTAAGGGGCATCAAA,1,137.752424,63217,63217,1.429255,0.531302,0.161096,63217,10184,0.551224,0,0.111127,0.013882,mMDA
GTGGTGATAGGAGTCTGCTAACTCACAGTAGCAAGGTTGGATGCA,1,137.244957,75850,75850,1.704385,0.728763,0.161094,75850,12219,0.666194,0,0.101716,0.022570,mMDA
TACCACAGAGGAGATACCGAACTCAGCATTGGAAGGGTCGGTAAA,1,138.331909,161291,161291,4.593797,0.004101,0.170009,161291,27421,1.173900,0,0.092074,0.008000,mMDA
GTGGTGATAGGAGGACGAATACTCAGACGAACAAGGGTTACGGTA,1,137.798189,402332,402332,1.825748,0.702868,0.171972,402332,69190,3.583872,0,0.068315,0.055362,mMDA
ATATGCGGAGGATACAGCAGACTCTAACGGAGAAGGGGCATCAAA,1,138.389468,125335,125335,1.660128,0.141111,0.163227,125335,20458,1.087417,0,0.067863,0.045960,mMDA
CGACAGTAAGGAAACTGCTCACTCTCCAGTCTAAGGCACTGACAA,1,138.410560,42084,42084,1.995385,0.964743,0.154215,42084,6490,0.381110,0,0.067681,0.012721,mMDA
ACCTCGTAAGGACGCTACTAACTCGGAACTGTAAGGCGGTAAGTA,1,137.804705,304175,304175,4.818117,0.959752,0.163271,304175,49663,2.730103,0,0.065585,0.053191,mMDA
TATCAGCCAGGAGTCTGCTAACTCCACCATCTAAGGGTGACTCTA,1,137.346724,272721,272721,8.316465,0.022167,0.196659,272721,53633,1.256623,0,0.058855,0.018320,mMDA
ATATGCGGAGGAACCTTCAGACTCAGACACCAAAGGTTGATGGCA,1,137.647087,27409,27409,4.011606,0.035904,0.169579,27409,4648,0.235170,0,0.054907,0.007674,mMDA
CGCTAGTTAGGATGGTCACTACTCAGGTCGTAAAGGGTAACCGAA,1,137.055406,250931,250931,14.258640,0.011885,0.155752,250931,39083,1.815086,0,0.046141,0.030065,PTA
CGACAGTAAGGAAACTGCTCACTCGGAACTGTAAGGGTCCGATTA,1,137.729720,168925,168925,14.463631,0.000593,0.154672,168925,26128,1.210148,0,0.043906,0.027477,PTA
ACCTCGTAAGGACACCTTGAACTCTCTGGAACAAGGTCCTCAACA,1,137.556174,167070,167070,3.624941,0.094339,0.155994,167070,26062,1.402610,0,0.041159,0.030078,PTA
AGGTCCAAAGGACGACAAGAACTCCAGGTGAAAAGGGTCCGATTA,1,137.423277,502706,502706,12.199365,0.022447,0.152783,502706,76805,2.903404,0,0.037920,0.024797,PTA
CAACCAACAGGAAGACCGATACTCTGCTATGGAAGGGTCCGATTA,1,137.453405,587793,587793,13.665994,0.002279,0.163612,587793,96170,3.432682,0,0.037431,0.027952,PTA
TATCAGCCAGGAGATACCGAACTCAGGACATCAAGGGTCCGATTA,1,135.967736,784066,784066,30.880658,0.007798,0.174388,784066,136732,3.321688,0,0.036503,0.025089,PTA
ATCGACAGAGGATTCGGTAGACTCAGACGAACAAGGACATCGTCA,1,137.587228,33825,33825,2.393305,0.348911,0.166563,33825,5634,0.288014,0,0.033290,0.009096,mMDA
CGCTAGTTAGGAAGATGGTCACTCTATGCGACAAGGGGCATCAAA,1,139.811684,4519,4519,1.955827,0.192868,0.151582,4519,685,0.033231,0,0.031553,0.000000,mMDA